server:
  port: 8080
  servlet:
    context-path : /test-softexpert

enderecos:
  picPay:
    url: https://appws.picpay.com/ecommerce/public/payments
  mercadoPago:
    url: https://api.mercadopago.com/v1/payments
    token: https://api.mercadopago.com/oauth/token